// Generated by CoffeeScript 1.6.3
(function() {
  var Base, crypto, fs, mkdirp, os, osenv, path;

  path = require('path');

  fs = require('fs');

  crypto = require('crypto');

  os = require('os');

  osenv = require('osenv');

  mkdirp = require('mkdirp');

  Base = (function() {
    function Base() {
      var tmp_dir, user;
      user = (osenv.user() || this.generate_fake_user()).replace(/\\/g, '-');
      tmp_dir = path.join((os.tmpdir ? os.tmpdir() : os.tmpDir()), user);
      this.config_dir = process.env.XDG_CONFIG_HOME || path.join(osenv.home() || tmp_dir, '.config/sprout');
      if (!fs.existsSync(this.config_dir)) {
        mkdirp.sync(this.config_dir);
      }
    }

    Base.prototype.path = function(name) {
      if (name == null) {
        name = '';
      }
      return path.join(this.config_dir, name);
    };

    Base.prototype.generate_fake_user = function() {
      var uid;
      uid = [process.pid, Date.now(), Math.floor(Math.random() * 1000000)].join('-');
      return crypto.createHash('md5').update(uid).digest('hex');
    };

    return Base;

  })();

  module.exports = Base;

}).call(this);
