export const CREATE_TOURNAMENT = 'CREATE_TOURNAMENT'
export const CREATE_TOURNAMENT_RESPONSE = 'CREATE_TOURNAMENT_RESPONSE'

export const REQUEST_TOURNAMENT = 'REQUEST_TOURNAMENT'
export const SET_TOURNAMENT = 'SET_TOURNAMENT'
export const SET_TOURNAMENT_FAILED = 'SET_TOURNAMENT_FAILED'
export const SET_TOURNAMENT_V1 = 'SET_TOURNAMENT_V1'
export const SAVE_TOURNAMENT_FAILED = 'SAVE_TOURNAMENT_FAILED'

export const NEW_ROUND = 'NEW_ROUND'
export const DELETE_ROUND = 'DELETE_ROUND'
