export const CREATE_TOURNAMENT = 'CREATE_TOURNAMENT'
export const CREATE_TOURNAMENT_RESPONSE = 'CREATE_TOURNAMENT_RESPONSE'

export const REQUEST_TOURNAMENT = 'REQUEST_TOURNAMENT'
export const SET_TOURNAMENT = 'SET_TOURNAMENT'
